name: k6 Performance Test API REGRESS.IN

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      test_type:
        description: 'Tipo de prueba'
        required: true
        default: 'smoke'
        type: choice
        options:
          - smoke
          - performance
          - spike
          - load
          - endurance
          - scalability
          - breakpoint
          - config-test
          - chaos-test

jobs:
  k6-tests:
    runs-on: ubuntu-latest
    env:
      USER: ${{ secrets.USER }}
      PASSWORD: ${{ secrets.PASSWORD }}

    strategy:
      matrix:
        include:
          - type: smoke
            path: test/api-regres-in/smoke/smoke-test.js
          - type: performance
            path: test/api-regres-in/stress/stress-test-csv.js
          - type: spike
            path: test/api-regres-in/spike/spike-test.js
          - type: load
            path: test/api-regres-in/load/load-test.js
          - type: endurance
            path: test/api-regres-in/endurance/endurance-test.js
          - type: scalability
            path: test/api-regres-in/scalability/scalability-test.js
          - type: breakpoint
            path: test/api-regres-in/breakpoint/breakpoint-test.js
          - type: config-test
            path: test/api-regres-in/config/config-test.js
          - type: chaos-test
            path: test/api-regres-in/regress/chaos-test.js

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install k6
        run: |
          sudo mkdir -p /usr/share/keyrings
          curl -s https://dl.k6.io/key.gpg | sudo gpg --dearmor -o /usr/share/keyrings/k6-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/k6-archive-keyring.gpg] https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
          sudo apt-get update
          sudo apt-get install -y k6

      - name: Run selected k6 test
        if: (github.event_name == 'workflow_dispatch' && matrix.type == github.event.inputs.test_type) || ((github.event_name == 'push' || github.event_name == 'pull_request') && matrix.type == 'smoke')
        env:
          K6_CLOUD_TOKEN: ${{ secrets.K6_CLOUD_TOKEN }}
        run: k6 run --out cloud ${{ matrix.path }}
