name: k6 Performance Test API REGRESS.IN

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      test_type:
        description: 'Tipo de prueba (smoke, performance, spike, load, endurance, scalability, breakpoint,config-test,chaos-test)'
        required: true
        default: 'smoke'

jobs:
  k6-tests:
    runs-on: ubuntu-latest
    
    env:
      USER: ${{ secrets.USER }}
      PASSWORD: ${{ secrets.PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install k6
        run: |
          sudo mkdir -p /usr/share/keyrings
          curl -s https://dl.k6.io/key.gpg | sudo gpg --dearmor -o /usr/share/keyrings/k6-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/k6-archive-keyring.gpg] https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
          sudo apt-get update
          sudo apt-get install -y k6

      - name: Run k6 smoke test
        if: github.event_name != 'workflow_dispatch' || inputs.test_type == 'smoke'
        run: k6 run test/api-regres-in/smoke/smoke-test.js

      - name: Run k6 performance test
        if: github.event_name == 'workflow_dispatch' && inputs.test_type == 'performance'
        env:
          K6_CLOUD_TOKEN: ${{ secrets.K6_CLOUD_TOKEN }}
        run: k6 run --out cloud test/api-regres-in/stress/stress-test-csv.js

      - name: Run k6 spike test
        if: github.event_name == 'workflow_dispatch' && inputs.test_type == 'spike'
        env:
          K6_CLOUD_TOKEN: ${{ secrets.K6_CLOUD_TOKEN }}
        run: k6 run --out cloud  test/api-regres-in/spike/spike-test.js

      - name: Run k6 load test
        if: github.event_name == 'workflow_dispatch' && inputs.test_type == 'load'
        env:
          K6_CLOUD_TOKEN: ${{ secrets.K6_CLOUD_TOKEN }}
        run: k6 run --out cloud  test/api-regres-in/load/load-test.js

      - name: Run k6 endurance test
        if: github.event_name == 'workflow_dispatch' && inputs.test_type == 'endurance'
        env:
          K6_CLOUD_TOKEN: ${{ secrets.K6_CLOUD_TOKEN }}
        run: k6 run --out cloud  test/api-regres-in/endurance/endurance-test.js

      - name: Run k6 scalability test
        if: github.event_name == 'workflow_dispatch' && inputs.test_type == 'scalability'
        env:
          K6_CLOUD_TOKEN: ${{ secrets.K6_CLOUD_TOKEN }}
        run: k6 run --out cloud  test/api-regres-in/scalability/scalability-test.js

      - name: Run k6 breakpoint test
        if: github.event_name == 'workflow_dispatch' && inputs.test_type == 'breakpoint'
        env:
          K6_CLOUD_TOKEN: ${{ secrets.K6_CLOUD_TOKEN }}
        run: k6 run --out cloud  test/api-regres-in/breakpoint/breakpoint-test.js
      
      - name: Run k6 config test
        if: github.event_name == 'workflow_dispatch' && inputs.test_type == 'config-test'
        env:
         K6_CLOUD_TOKEN: ${{secrets.K6_CLOUD_TOKEN}}
        run: k6 run --out cloud  test/api-regres-in/config/config-test.js

      - name: Run k6 chaos test
        if: github.event_name == 'workflow_dispatch' && inputs.test_type == 'chaos-test'
        env:
          K6_CLOUD_TOKEN: ${{ secrets.K6_CLOUD_TOKEN }}
        run: k6 run --out cloud test/api-regres-in/regress/chaos-test.js