name: k6 Performance Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  k6-tests:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Clonar el repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # Paso 2: Instalar k6 (solo una vez)
      - name: Install k6
        run: |
          sudo mkdir -p /usr/share/keyrings
          curl -s https://dl.k6.io/key.gpg | sudo gpg --dearmor -o /usr/share/keyrings/k6-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/k6-archive-keyring.gpg] https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list
          sudo apt-get update
          sudo apt-get install -y k6

      # Paso 3: Ejecutar el smoke test
      - name: Run k6 smoke test
        run: k6 run smoke-test.js

      # Paso 4: Ejecutar el performance test si smoke pasa
      - name: Run k6 performance test
        env:
          K6_CLOUD_TOKEN: ${{ secrets.K6_CLOUD_TOKEN }}
        run: k6 run --out cloud stress-test-csv.js